### ISSUE TITLE
Upgrade to preview 9

### ISSUE THREAD

**Issue by Lupusa87** [wtulloch/Blazor.IndexedDB#10]
After upgrading my app to preview 9 I get this error.
 
  I guess it is related to rename DotNetObjectRef with DotNetObjectReference following by [blog](https://devblogs.microsoft.com/aspnet/asp-net-core-and-blazor-updates-in-net-core-3-0-preview-9/)

  Are you going to update this repo to P9?

 Thank you in advance.

![Untitled](https://user-images.githubusercontent.com/40779557/64808286-f11a7680-d564-11e9-9919-ab6ee8eafe9c.png)

**Comment by wtulloch** [comment]
Hi there,

A pull request has already been submitted for this. I will update the Nuget package this week end.

Cheers,
Bill

Sent from Mail for Windows 10

From: Vakhtangi Abashidze
Sent: Friday, 13 September 2019 3:58 AM
To: wtulloch/Blazor.IndexedDB
Cc: Subscribed
Subject: [wtulloch/Blazor.IndexedDB] Upgrade to preview 9 (#10)

After upgrading my app to preview 9 I get this error.
I guess it is related to rename DotNetObjectRef with DotNetObjectReference following by blog
Are you going to update this repo to P9?
Thank you in advance.

**Comment by edgarssults** [comment]
@wtulloch Any luck with the package update?

**Comment by wtulloch** [comment]
@edgarssults  the Updated package has been published.

**Comment by edgarssults** [comment]
Excellent, thanks!


________________________________
