### ISSUE TITLE
Update NuGet to latest version

### ISSUE THREAD

**Issue by Reshiru** [wtulloch/Blazor.IndexedDB#4]
First of all thanks for your great work c: Really saves me some headache :)

I just would like to ask you if would maybe be able to update the version on the NuGet server too?
Currently: https://www.nuget.org/packages/TG.Blazor.IndexedDB/0.6.0-beta 

Related to: #3

Thanks in advance and kind regards c:

**Comment by wtulloch** [comment]
Thanks for the feedback. Yes I am planning to update the NuGet package, probably in the next day or so. Once that is done will close this.
Cheers,
Bill

**Comment by Reshiru** [comment]
Great, thank you :)

**Comment by wtulloch** [comment]
Updated Nuget Package to 0.9.0
