### ISSUE TITLE
Question - can we add store inside application or only inside ConfigureServices

### ISSUE THREAD

**Issue by Lupusa87** [wtulloch/Blazor.IndexedDB#6]
**I can't add new store inside application, is it possible only in startup?**

I want dynamically to create store and save data inside, based on API returned different data.

```
services.AddIndexedDB(dbStore =>
            {
                dbStore.DbName = "TheFactory"; //example name
                dbStore.Version = 1;

            dbStore.Stores.Add(new StoreSchema
            {
                Name = "Employees",
                PrimaryKey = new IndexSpec { Name = "id", KeyPath = "id", Auto = true },
                Indexes = new List<IndexSpec>
                    {
                        new IndexSpec{Name="firstName", KeyPath = "firstName", Auto=false},
                        new IndexSpec{Name="lastName", KeyPath = "lastName", Auto=false}

                    }
            });
                dbStore.Stores.Add(new StoreSchema
                {
                    Name = "Outbox",
                    PrimaryKey = new IndexSpec { Auto = true }
                }
                    );
            });
```

**Comment by wtulloch** [comment]
Currently start-up is the only way to add a new store. If you think there is a good case for doing it within the application I can probably add that capability.

**Comment by Lupusa87** [comment]
Thank you.

It will be great if it could be possible.

My current case is following:

My app has multi language interface, I have languages list and all words by languages in server db.
When user switches language words for selected language are downloaded and stored in indexedDB.
For example if user selected Spanish all Spanish words will be downloaded and saved in store e.g. - SpanishWordsStore, or if German in store e.g. - GermanWordsStore.

I don't save them in one store or owerrite because user can switch back again and I want to have separated words by language.

Alternative can be adding language name in each json documents and then filter but it will be slower.

Available Languages can be added on server and I don't want to have hard coded stores, rather create them inside code as required.

This is not perfect use case (this is for demo purposes) but it can explain why I faced need to create store in code.

**Comment by wtulloch** [comment]
Just to let you know I have got this working in principle. My only concern at the moment is the solution requires incrementing the data version number which will mean that it will not align with the version number in the startup code. I need to determine whether this would be a problem or not.

**Comment by wtulloch** [comment]
Hi,
Just to let you know have released an updated to the Library that provide the means to add a new store dynamically.

**Comment by Lupusa87** [comment]
Thank you, I will check it later.
