### ISSUE TITLE
Blazor preview 8

### ISSUE THREAD

**Issue by aeastham67** [wtulloch/Blazor.IndexedDB#8]
Hi,

This is a great project which I've been experimenting with. Thanks for your efforts.

I've updated my project to preview 8 of .net core 3 and blazor as this supposedly won't have any more breaking changes. Unfortunately, I haven't been able to include your package or work out how to build your source code with preview 8. I keep getting a linker error. Are you looking into getting this to work with the latest preview? I appreciate you may be busy at the moment but it would be useful to know if you are intending to do this.

Thanks very much,

Best regards,

Andy Eastham

**Comment by wtulloch** [comment]
Hi Andy,
Will get on to it in the next day or so.
Will let you know when it is done.
Cheers,
Bill

**Comment by wtulloch** [comment]
Have updated the source code to preview 8 and have published an updated Nuget package

**Comment by aeastham67** [comment]
Thank you so much.

Andy
